export default [{
    adult: false,
    backdrop_path: "/xFxk4vnirOtUxpOEWgA1MCRfy6J.jpg",
    genre_ids: [12,16,15],
    id: 508439,
    original_language: "en",
    original_title: "Onward",
    overview: "In a suburban fantasy world, two teenage elf brothers embark on an extraordinary quest to discover if there is still a little magic left out there.",
    popularity: 88.444,
    poster_path: "/f4aul3FyD3jv3v4bul1IrkWZvzq.jpg",
    release_date: "2020-02-29",
    title: "Onward",
    video: false,
    vote_average: 2,
    vote_count: 2226,
},
{
    adult: false,
    backdrop_path: "/ocUrMYbdjknu2TwzMHKT9PBBQRw.jpg",
    genre_ids:[28, 878],
    id: 338762,
    original_language: "en",
    original_title: "Bloodshot",
    overview: "After he and his wife are murdered, marine Ray Garrison is resurrected by a team of scientists. Enhanced with nanotechnology, he becomes a superhuman, biotech killing machine—'Bloodshot'. As Ray first trains with fellow super-soldiers, he cannot recall anything from his former life. But when his memories flood back and he remembers the man that killed both him and his wife, he breaks out of the facility to get revenge, only to discover that there's more to the conspiracy than he thought.",
    popularity: 81.568,
    poster_path: "/8WUVHemHFH2ZIP6NWkwlHWsyrEL.jpg",
    release_date: "2020-03-05",
    title: "Bloodshot",
    video: false,
    vote_average: 2,
    vote_count: 2636,
},
{ 
    adult: false,
    backdrop_path: "/ww7eC3BqSbFsyE5H5qMde8WkxJ2.jpg",
    genre_ids: [28, 27, 878, 53],
    id: 443791,
    original_language: "en",
    original_title: "Underwater",
    overview: "After an earthquake destroys their underwater station, six researchers must navigate two miles along the dangerous, unknown depths of the ocean floor to make it to safety in a race against time.",
    popularity: 43.731,
    poster_path: "/gzlbb3yeVISpQ3REd3Ga1scWGTU.jpg",
    release_date: "2020-01-08",
    title: "Underwater",
    video: false,
    vote_average: 3,
    vote_count: 1300
}
]
